BUILD ?= build

all:
	@echo
	@echo "----- GOFS BUILD DONE -----"

tests:
	@echo
	@echo "----- GOFS TESTS BUILD DONE -----"

examples:
	@echo
	@echo "----- GOFS EXAMPLES BUILD DONE -----"

.PHONY: all tests examples
