BUILD ?= build

all:
	@echo "----- GOFS BUILD DONE -----"

tests:
	@echo "----- GOFS TESTS BUILD DONE -----"

examples:
	@echo "----- GOFS EXAMPLES BUILD DONE -----"

clean:
	@-rm -rf $(BUILD)

.PHONY: all clean tests examples
