BUILD ?= build

all:
	@echo
	@echo "----- ALLOCS BUILD DONE -----"

tests:
	@echo
	@echo "----- ALLOCS TESTS BUILD DONE -----"

examples:
	@echo
	@echo "----- ALLOCS EXAMPLES BUILD DONE -----"

.PHONY: all tests examples
