BUILD ?= build

all:
	@echo "----- ALLOCS BUILD DONE -----"

tests:
	@echo "----- ALLOCS TESTS BUILD DONE -----"

examples:
	@echo "----- ALLOCS EXAMPLES BUILD DONE -----"

clean:
	@-rm -rf $(BUILD)

.PHONY: all clean tests examples
