BUILD ?= build

all:
	@echo
	@echo "----- OBJS BUILD DONE -----"

tests:
	@echo
	@echo "----- OBJS TESTS BUILD DONE -----"

examples:
	@echo
	@echo "----- OBJS EXAMPLES BUILD DONE -----"

.PHONY: all tests examples
